version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    #Añade el archvio de configurarcion promtheus.yml
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
#Obtiene datos de los demas contenedores
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    expose:
      - 9100
#Obtiene datos de los demas contenedores
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
  
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: usuario
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario
    volumes:
     - db_data:/var/lib/mysql
#Visualiza los datos que obtiene de Prometheus
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 9000:3000
    links:
      - prometheus:prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    #Variables de entorno que modifican el archivo grafana.ini
    environment:
    #Activo el SMTP de Grafana
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp-mail.outlook.com:587
      - GF_SMTP_USER=jok_zed@hotmail.com
      - GF_SMTP_PASSWORD=
      - GF_SMTP_FROM_ADDRESS=jok_zed@hotmail.com
volumes:
  grafana-data:
  db_data: